### ISSUE TITLE
test_compat_rx in test_resolvers spuriously fails

### ISSUE THREAD

**Issue by alvaromorales** [fakedrake/WikipediaBase#48]
Is there a race condition in how tests in tests/examples.py are read? See output below.

```
======================================================================
FAIL: test_compat_rx (tests.test_resolvers.TestResolvers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "..../pywikipediabase/tests/test_resolvers.py", line 96, in test_compat_rx
    self.assertRegexpMatches(ans, rx, msg=msg)
AssertionError:
Query: '(get "wikipedia-ocean" "Sea of Azov" (:CODE "AREA"))'
Answer: '((:CODE "180 km (110 mi)"))'
Matcher: '39.?000.*km.*2.*15.?000.*sq.*mi'
Completion: 27\37: '39.?000.*km.*2.*15.?000.*sq.*mi' not found in u'((:CODE "180 km (110 mi)"))'
```

Looks like an off-by-one error, the wrong matcher is being applied. This test is spurious (it doesn't always fail).

**Comment by alvaromorales** [comment]
Looks like the wrong message is being echoed. The spurious error is:

```
======================================================================
FAIL: test_compat_rx (tests.test_resolvers.TestResolvers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../WikipediaBase/tests/test_resolvers.py", line 96, in test_compat_rx
    self.assertRegexpMatches(ans, rx)
AssertionError: Regex didn't match: '14.*m.*46.*ft' not found in u'((:CODE "7 metres (23 ft)"))'
```

It occurs about once every 10 runs, between checking for DEPTH and MAX-DEPTH for "Sea of Azov".

**Comment by fakedrake** [comment]
Sorry i am slow on replying, i am not at home these days. I have
encountered and briefly investigated this but couldn't isolate it. There is
no async or parallelism involved in wikibase (not explicitly at least) so
the tests should be in that sense be deterministic.  I have no idea why
this happens...

**Comment by fakedrake** [comment]
Now that i think of it it might be a race condition internal to lxml but
then we should have random tests failing all over the place. This is too
consistent. Also afaik lxml doesnt use threads either, but i may be wrong.

**Comment by alvaromorales** [comment]
#35 first described this bug
